from django.contrib import admin
from .models import *

admin.site.register(Banner)
admin.site.register(Navbar)
admin.site.register(News)
admin.site.register(Game_schedule)
admin.site.register(Calendar)
admin.site.register(Schedule)
admin.site.register(Player_statistics)
admin.site.register(Shop_1)
admin.site.register(Shop_2)
admin.site.register(Shop_3)
admin.site.register(About_shop)
admin.site.register(Stadium_photo)
admin.site.register(Stadium)
admin.site.register(Arena_history)
admin.site.register(Arena_history2)
admin.site.register(Arena_history3)
admin.site.register(Partners)
admin.site.register(Team_members)
admin.site.register(Management)
admin.site.register(Coach)
admin.site.register(Club_info)
admin.site.register(Club_history)
admin.site.register(Recommendations)
admin.site.register(Academy)
admin.site.register(Training)
admin.site.register(Bobur_arena)